# Generated by Django 2.0 on 2019-07-08 13:39

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='files/input_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'pdf', 'txt', 'ppt', 'pptx', 'xls', 'xlsx', 'doc', 'docx'))])),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='files/converted_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'pdf', 'txt', 'ppt', 'pptx', 'xls', 'xlsx', 'doc', 'docx'))])),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('has_error', models.BooleanField(default=False)),
                ('input_file_type', models.CharField(choices=[('jpg', 'JPG'), ('png', 'PNG'), ('pdf', 'PDF'), ('txt', 'TXT'), ('ppt', 'PPT'), ('pptx', 'PPTX'), ('doc', 'DOC'), ('docx', 'DOCX'), ('XLS', 'XLS'), ('xlsx', 'XLSX')], max_length=4)),
                ('converted_file_type', models.CharField(blank=True, choices=[('jpg', 'JPG'), ('png', 'PNG'), ('pdf', 'PDF'), ('txt', 'TXT'), ('ppt', 'PPT'), ('pptx', 'PPTX'), ('doc', 'DOC'), ('docx', 'DOCX'), ('XLS', 'XLS'), ('xlsx', 'XLSX')], max_length=4)),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
